### PR TITLE
Changes to support building on an M1 mac

### PR DESCRIPTION
**Pull request by leonid-s-usov**
This PR is supporting https://github.com/ceph/ceph/pull/52629

### CODE REVIEW

**Comment by leonid-s-usov** [comment]
@mdw-at-linuxbox @PeterHamilton Hi! Not sure who to tag, so tagging the recent contributors. Can this be reviewed and merged, please?

**Review by mattbenjamin — APPROVED** [review]
these changes look valid to me

**Comment by leonid-s-usov** [comment]
@mattbenjamin who can merge this PR? also, should it be merged to the `wip-morestuff` branch?

**Comment by mattbenjamin** [comment]
I believe this PR should be targeting ceph:main, not ceph:wip-morestuff (whatever that is).  If it did, I could add labels and assign it, and, yes merge it.  Our process is that it should pass build checks and a teuthology ci run before someone merges it.

**Comment by leonid-s-usov** [comment]
The issue is that the current `ceph/main` branch references a commit in the `wip-morestuff` branch, namely b25cde94c9b8686988ed1236bd807afe74991333, which is why I have pushed to it.

```
 » git ls-tree origin/main:src | grep libkmip
160000 commit b25cde94c9b8686988ed1236bd807afe74991333  libkmip
```

~~I can re-submit this PR against the main branch~~, but not sure how easy it will be to then update the ceph repo submodule to incorporate it. UPD: I can't resubmit to the main branch because this repo only has this `wip-morestuff` branch 🤷🏻‍♂️

**Comment by mattbenjamin** [comment]
ok, maybe that makes sense, but my github permissions don't let me do anything with this PR
@mdw-at-linuxbox @jdurgin could somebody assist here?

**Comment by mattbenjamin** [comment]
(this is against libkmip, which is a submodule--I can't say why that submodule has wip-morestuff as a branch, but it appears to)

**Comment by mdw-at-linuxbox** [comment]
"wip-morestuff" was never intended to be a production branch of any sort - at the time I pushed I think I was imagining a more active engagemen with its original upstream and more activity on the ceph side too.  Obviously that never happened.

I've pushed out a new "ceph-main" branch with your change.  "wip-morestuff" had one other centos related change that might not matter, but I'll carry it forward regardless.  I'll make a PR for ceph proper to update the submodule reference; it will need to be tested in teuthology (at least) before it becomes official.  Meanwhile, you should certainly do whatever testing you want with M1.

**Comment by mdw-at-linuxbox** [comment]
I've made this PR https://github.com/ceph/ceph/pull/53668 to pull the changes into ceph main.

**Comment by leonid-s-usov** [comment]
Thanks @mdw-at-linuxbox! I'll post on the mentioned PR once my local tests pass. I'll close this PR now.

**Pull request closed without merging**
